package mqmsgapppackage;


//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JPanel;

public class UserGUI extends JPanel {
  private JButton jcomp1;
  private JButton jcomp2;
  private JButton jcomp3;
  private JButton jcomp4;

  public UserGUI() {
      //construct components
      jcomp1 = new JButton ("Write message to MQ queue");
//      make this button do something.
      jcomp1.addActionListener(new ActionListener() 
      {
          public void actionPerformed(ActionEvent e) 
          {
            // Code to be executed when Option  is selected
//        	  instantiate the queuewriter before we can use it
        	  QueueWriter queuewriter = new QueueWriter();
//        	call the queue writer.
        	  queuewriter.queueWriter();
          }
      }
      
      jcomp2 = new JButton ("Button 2");
      jcomp3 = new JButton ("Button 3");
      jcomp4 = new JButton ("Button 4");

      //adjust size and set layout
      setPreferredSize (new Dimension (300, 245));
      setLayout (null);

      //add components
      add (jcomp1);
      add (jcomp2);
      add (jcomp3);
      add (jcomp4);

      //set component bounds (only needed by Absolute Positioning)
      jcomp1.setBounds (25, 35, 100, 20);
      jcomp2.setBounds (25, 70, 100, 20);
      jcomp3.setBounds (25, 105, 100, 20);
      jcomp4.setBounds (25, 140, 100, 25);
      
//      make the buttons do things
      

      
  }


  public static void Execute (String[] args) {
      JFrame frame = new JFrame ("MyPanel");
      frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
      frame.getContentPane().add (new UserGUI());
      frame.pack();
      frame.setVisible (true);
  }
}
